name:                HaskellBindElm
version:             0.1.0.0
#synopsis:
#description:
homepage:            https://github.com/githubuser/HaskellBindElm#readme
license:             BSD3
author:              Author name here
maintainer:          example@example.com
copyright:           2018 Author name here
category:            Web
extra-source-files:
- README.md

dependencies:
  - base >= 4.7 && < 5

tests:
  test: 
    source-dirs: 
      - test
    main: Test.hs
    dependencies: 
      - base
      - tasty 
      - tasty-hunit
      - tasty-smallcheck 
      - tasty-quickcheck
      - tasty-hspec
      - HaskellBindElm

executables:
  HaskellBindElm:
    source-dirs:      src
    main:             Main.hs
